services:
  - type: web
    name: disease-diagnosis-system
    runtime: python
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "gunicorn --chdir app app_deployment:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: PYTHON_SETUPTOOLS_UNSAFE_INSTALL
        value: "1"
